services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql://root:rootpassword@mysql:3306/airflow_db
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - MYSQLCLIENT_CFLAGS=-I/usr/include/mysql
      - MYSQLCLIENT_LDFLAGS=-L/usr/lib/mysql
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    command: /bin/bash -c "airflow db init && airflow webserver -p 8080 & airflow scheduler"

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=airflow_db
      - MYSQL_INITDB_SKIP_TZINFO=1
    command: --sql-mode=""
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"


volumes:
  mysql_data:
